package database
























































































}	fmt.Println("MongoDB indexes created/verified")	}		log.Printf("failed to create index on transactionId: %v", err)	if err != nil {	_, err = db.Collection("payments").Indexes().CreateOne(ctx, transactionIndex)	}		}),			"transactionId": 1,		Keys: options.Index().SetUnique(true).Keys(map[string]int{	transactionIndex := mongo.IndexModel{	// Index on transactionId	}		log.Printf("failed to create index on patientId: %v", err)	if err != nil {	_, err = db.Collection("payments").Indexes().CreateOne(ctx, patientIndex)	}		}),			"patientId": 1,		Keys: options.Index().SetUnique(false).Keys(map[string]int{	patientIndex := mongo.IndexModel{	// Index on patientId	}		log.Printf("failed to create index on appointmentId: %v", err)	if err != nil {	_, err := db.Collection("payments").Indexes().CreateOne(ctx, indexModel)	}		}),			"appointmentId": 1,		Keys: options.Index().SetUnique(false).Keys(map[string]int{	indexModel := mongo.IndexModel{	// Index on appointmentId	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)func CreateIndexes(db *mongo.Database) {// CreateIndexes creates necessary MongoDB indexes}	return db	log.Println("MongoDB connected successfully to payment-db")	CreateIndexes(db)	// Create indexes	PaymentDB = db	db := client.Database("payment-db")	}		log.Fatalf("failed to ping MongoDB: %v", err)	if err != nil {	err = client.Ping(ctx, nil)	// Verify connection	}		log.Fatalf("failed to connect to MongoDB: %v", err)	if err != nil {	client, err := mongo.Connect(ctx, options.Client().ApplyURI(mongoURI))	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)	}		log.Fatalf("DATABASE_URL environment variable not set")	if mongoURI == "" {	mongoURI := os.Getenv("DATABASE_URL")func Connect() *mongo.Database {// Connect connects to MongoDB and initializes the databasevar PaymentDB *mongo.Database)	"go.mongodb.org/mongo-driver/mongo/options"	"go.mongodb.org/mongo-driver/mongo"	"time"	"os"	"log"	"fmt"	"context"import (