apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location /health {
          return 200 'OK';
        }

        location /api/auth/ {
          proxy_pass http://auth-service:8081/;
        }

        location /api/patients/ {
          proxy_pass http://patient-service:5002/;
        }

        location /appointments {
          proxy_pass http://appointment-service:8083;
        }

        location /doctors {
          proxy_pass http://doctor-service:8082;
        }

        location /notifications {
          proxy_pass http://notification-service:8084;
        }
      }
    }